import { ArrowLeft, Check } from "lucide-react";
import Link from "next/link";

import TournamentInformationForm from "@/components/admin/TournamentInformationForm";
import TournamentResetForm from "@/components/admin/TournamentResetForm";
import {
  getTournamentResetPreview,
  isTournamentResetEnabled,
} from "@/lib/tournament-reset";
import {
  getNextUpcomingTournament,
  getTournamentByIdentifier,
} from "@/lib/tournaments";

interface TournamentAdminPageProps {
  searchParams: Promise<{
    tournament?: string | string[];
    reset?: string;
    resetError?: string;
  }>;
}

export const dynamic = "force-dynamic";

export default async function TournamentAdminPage({
  searchParams,
}: TournamentAdminPageProps) {
  const params = await searchParams;
  const requestedTournament = Array.isArray(params.tournament)
    ? params.tournament[0]
    : params.tournament;

  let tournament = null;
  let resetPreview = null;
  const resetEnabled = isTournamentResetEnabled();
  let loadFailed = false;

  try {
    tournament = requestedTournament
      ? await getTournamentByIdentifier(requestedTournament)
      : await getNextUpcomingTournament();
    resetPreview = tournament
      ? await getTournamentResetPreview(tournament.id)
      : null;
  } catch (error) {
    console.error("Tournament Information page load failed.", error);
    loadFailed = true;
  }

  return (
    <>
      <Link
        href={
          tournament
            ? `/admin/tournament-manager?tournament=${encodeURIComponent(tournament.slug || tournament.id)}`
            : "/admin/tournament-manager"
        }
        className="inline-flex min-h-11 items-center gap-2 text-xs font-black uppercase tracking-[0.14em] text-neutral-400 transition-colors hover:text-[#D4A017] focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[#D4A017]"
      >
        <ArrowLeft aria-hidden="true" className="size-4" />
        Back to Tournament Manager
      </Link>

      <div className="mt-6 border-b border-white/10 pb-6">
        <p className="text-xs font-black uppercase tracking-[0.2em] text-red-500">
          Management
        </p>
        <h1 className="mt-2 text-3xl font-black uppercase tracking-tight text-white sm:text-4xl">
          Tournament Information
        </h1>
      </div>

      {tournament ? (
        <>
          <aside className="mt-6 border border-[#4A3A12] bg-[#D4A017]/5 p-5">
            <p className="text-xs font-black uppercase tracking-[0.14em] text-[#D4A017]">
              This information appears on
            </p>
            <ul className="mt-3 grid gap-2 text-sm text-neutral-300 sm:grid-cols-3">
              {[
                "Homepage Featured Tournament",
                "Tournament Schedule",
                "Tournament Details",
              ].map((item) => (
                <li key={item} className="flex items-center gap-2">
                  <Check
                    aria-hidden="true"
                    className="size-4 text-emerald-400"
                  />
                  {item}
                </li>
              ))}
            </ul>
          </aside>
          <div className="mt-6">
            <TournamentInformationForm
              key={tournament.id}
              tournament={tournament}
            />
          </div>
          {params.reset === "1" && (
            <p className="mt-6 border border-emerald-500/30 bg-emerald-500/10 px-4 py-3 text-sm font-semibold text-emerald-300" role="status">
              Tournament reset completed successfully.
            </p>
          )}
          {params.resetError === "confirmation" && (
            <p className="mt-6 border border-red-500/30 bg-red-500/10 px-4 py-3 text-sm text-red-300" role="alert">
              Tournament reset confirmation was incomplete or did not match.
            </p>
          )}
          {resetPreview && (
            <section className="mt-10 border border-red-500/30 bg-[#111111] p-5 sm:p-7">
              <p className="text-xs font-black uppercase tracking-[0.16em] text-red-400">
                Danger Zone
              </p>
              <h2 className="mt-2 text-xl font-black uppercase text-white">
                Reset Tournament Activity
              </h2>
              <p className="mt-3 max-w-3xl text-sm leading-6 text-neutral-400">
                Permanently remove activity generated by this tournament while preserving its setup, Membership Season, and all member records.
              </p>
              <TournamentResetForm
                tournamentId={tournament.id}
                tournamentName={tournament.name}
                counts={resetPreview}
                enabled={resetEnabled}
              />
            </section>
          )}
        </>
      ) : (
        <section className="mt-6 border border-white/10 bg-[#111111] p-6">
          <h2 className="text-xl font-black uppercase text-white">
            {loadFailed
              ? "Tournament Information Unavailable"
              : requestedTournament
                ? "Tournament Not Found"
                : "No Tournaments Yet"}
          </h2>
          <p className="mt-3 text-sm leading-6 text-neutral-400">
            {loadFailed
              ? "We could not load this tournament. Please try again."
              : requestedTournament
                ? "We could not load this tournament."
                : "No tournaments have been created yet."}
          </p>
        </section>
      )}
    </>
  );
}
