"use client";

import { useRef, useState } from "react";
import { resetTournamentAction } from "@/app/admin/tournament-manager/reset/actions";
import type { TournamentResetCounts } from "@/lib/tournament-reset";

export default function TournamentResetForm({
  tournamentId,
  tournamentName,
  counts,
  enabled,
}: {
  tournamentId: string;
  tournamentName: string;
  counts: TournamentResetCounts;
  enabled: boolean;
}) {
  const [acknowledged, setAcknowledged] = useState(false);
  const [confirmation, setConfirmation] = useState("");
  const dialogRef = useRef<HTMLDialogElement>(null);
  const expected = `RESET ${tournamentName.toUpperCase()}`;
  const ready = acknowledged && confirmation === expected;

  return (
    <>
      <button
        type="button"
        disabled={!enabled}
        onClick={() => dialogRef.current?.showModal()}
        className="mt-5 inline-flex min-h-11 items-center justify-center border border-red-500/50 px-5 text-xs font-black uppercase tracking-[0.12em] text-red-300 transition hover:border-red-500 hover:bg-red-500/10 disabled:cursor-not-allowed disabled:border-white/10 disabled:text-neutral-600 disabled:hover:bg-transparent"
      >
        Reset Tournament
      </button>
      {!enabled && (
        <p className="mt-3 text-xs leading-5 text-neutral-500">
          Tournament Reset is disabled in production. Set{" "}
          <code>ENABLE_PRODUCTION_TOURNAMENT_RESET=true</code> to enable it.
        </p>
      )}

      <dialog
        ref={dialogRef}
        aria-labelledby="reset-dialog-title"
        className="m-auto w-[min(92vw,42rem)] border border-red-500/40 bg-[#111111] p-0 text-white backdrop:bg-black/80"
        onClose={() => {
          setAcknowledged(false);
          setConfirmation("");
        }}
      >
        <form action={resetTournamentAction} className="p-5 sm:p-7">
          <input type="hidden" name="tournamentId" value={tournamentId} />
          <p className="text-xs font-black uppercase tracking-[0.16em] text-red-400">
            Permanent Tournament Activity Reset
          </p>
          <h2 id="reset-dialog-title" className="mt-2 text-2xl font-black uppercase text-white">
            Reset {tournamentName}?
          </h2>
          <p className="mt-4 text-sm leading-6 text-neutral-300">
            This permanently removes activity generated by this tournament:
          </p>
          <ul className="mt-3 space-y-2 text-sm text-neutral-300">
            <li>{counts.registrations} registrations and registration-history records</li>
            <li>{counts.resultEntries} WeighFish import rows</li>
            <li>{counts.publishedResults} official result records, including winner and Big Bass selections</li>
            <li>{counts.aoyContributions} AOY or qualification contribution records</li>
            <li>Temporary winner photos, Big Bass photos, and tournament import files</li>
          </ul>
          <p className="mt-5 border border-[#D4A017]/30 bg-[#D4A017]/10 px-4 py-3 text-sm font-bold text-neutral-100">
            Members, Membership Seasons, and Tournament Configuration are NOT affected.
          </p>
          <label className="mt-5 flex gap-3 text-sm text-neutral-200">
            <input name="acknowledged" type="checkbox" checked={acknowledged} onChange={(event) => setAcknowledged(event.target.checked)} className="mt-0.5 size-4 accent-red-600" />
            <span>I understand this removes tournament activity but does not remove members.</span>
          </label>
          <label className="mt-5 block text-xs font-black uppercase tracking-[0.12em] text-neutral-300">
            Type {expected}
            <input name="confirmation" value={confirmation} onChange={(event) => setConfirmation(event.target.value)} autoComplete="off" className="mt-2 min-h-11 w-full border border-white/15 bg-black px-3 text-white outline-none focus:border-red-500" />
          </label>
          <div className="mt-6 flex flex-col-reverse gap-3 sm:flex-row sm:justify-end">
            <button type="button" onClick={() => dialogRef.current?.close()} className="min-h-11 border border-white/15 px-5 text-xs font-black uppercase text-neutral-300">
              Cancel
            </button>
            <button disabled={!ready} className="min-h-11 bg-red-600 px-5 text-xs font-black uppercase text-white disabled:cursor-not-allowed disabled:opacity-40">
              Reset Tournament
            </button>
          </div>
        </form>
      </dialog>
    </>
  );
}
